#ifndef STANDARDLOOP_TODO_H
#define STANDARDLOOP_TODO_H

#define STANDARDLOOP_TODO_H_MAJOR_VERSION 0
#define STANDARDLOOP_TODO_H_MINOR_VERSION 0
#define STANDARDLOOP_TODO_H_PATCH_VERSION 0
#define STANDARDLOOP_TODO_H_VERSION "0.0.0"

#endif
